const express = require("express")
const bodyParser = require("body-parser")
const routes = require("./routes/index")
const cors = require("cors")
const app = express()
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app.use(cors())
routes(app)
app.listen(8080)
